name: Build FreeBSD World

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile FreeBSD world

    steps:
      - name: Checkout code (this repo)
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            debootstrap bsdextrautils clang lld libarchive-dev libbz2-dev libelf-dev \
            zlib1g-dev libssl-dev python3 bmake git xz-utils flex byacc time

      - name: Cache FreeBSD source
        id: cache-freebsd
        uses: actions/cache@v4
        with:
          path: freebsd-src
          key: freebsd-src-releng-14.1-${{ hashFiles('freebsd-src/.git/HEAD') }}
          restore-keys: |
            freebsd-src-releng-14.1-

      - name: Clone FreeBSD (if cache miss)
        if: steps.cache-freebsd.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 --branch releng/14.1 https://git.freebsd.org/src.git freebsd-src

      - name: Build world
        run: |
          mkdir -p obj
          cd freebsd-src
          MAKEOBJDIRPREFIX=$PWD/../obj ./tools/build/make.py \
          --cross-bindir=/usr/bin \
          -j$(nproc) \  
            TARGET=amd64 TARGET_ARCH=amd64 buildworld

      - name: Package result
        run: |
          mkdir -p $HOME/artifacts
          tar czf $HOME/artifacts/freebsd-build.tar.gz -C obj .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: freebsd-build
          path: ~/artifacts/freebsd-build.tar.gz
